services:

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"      
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/certs:/etc/nginx/certs  
    restart: unless-stopped
    networks:
      - website-network
    
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/var/www/html
    depends_on:
      - reverse-proxy
    restart: unless-stopped
    networks:
      - website-network
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9000"
    volumes:
      - ./frontend/html:/var/www/html
    networks:
      - website-network

  mysql-active:
    image: mysql/mysql-server:latest
    container_name: mysql-active
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: jG31"8|y5{:Mj4o+Ga?~
    ports:
      - "3306"
    volumes:
      - mysql-active-data:/var/lib/mysql
    networks:
      - website-network

  mysql-backup:
    image: mysql/mysql-server:latest
    container_name: mysql-backup
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 49tB8UR;{jd^++le=8.1
    ports:
      - "3307"
    volumes:
      - mysql-backup-data:/var/lib/mysql
    networks:
      - website-network


volumes:
  jenkins_home:
  certs:
    driver: local
  mysql-active-data:
  mysql-backup-data:

networks:
  website-network: {}
